[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm exec vite build"]

[start]
cmd = "pnpm dlx serve dist -p $PORT"
